sudo: required
language: python
services:
  - docker
python:
  - "2.7"
install:
  - docker build -f tests/Dockerfile -t txgio/anki-connect .
script:
  - docker run -ti -d --rm -p 8765:8765 txgio/anki-connect
  - >
    curl localhost:8765 -X POST -s -d '{"action": "version"}'