sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install:
  - docker build -f tests/Dockerfile -t txgio/anki-connect .
script:
  - curl localhost:8765 -X POST -s -d '{"action": "version"}'