sudo: required
language: python
addons:
  hosts:
    - docker
services:
  - docker
python:
  - "2.7"
install:
  - docker build -f tests/docker/Dockerfile -t txgio/anki-connect .
script:
  - docker run -ti -d --rm -p 8888:8765 -e ANKICONNECT_BIND_ADDRESS=0.0.0.0 txgio/anki-connect
  - ./tests/scripts/wait-up.sh http://docker:8888
  - python -m unittest discover -s tests -v